spring.application.name=microserviceeureka
server.port=9999

#Se desactiva replicacion de Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.max-threads-for-peer-replication=0



