spring.application.name=MicroserviceGateway
server.port=8888

#Eureka configuration
eureka.client.service-url.defaultZone=http://localhost:9999/eureka

#Microservicepet routing
# Nombre del microservicio
spring.cloud.gateway.server.webflux.routes[0].id=microservicepet
# Eureka LoadBalancer (lb)
spring.cloud.gateway.server.webflux.routes[0].uri=lb://microservicepet
# Rutas de acceso para dirigir el trafico (path)
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/pet/**

#Microserviceadopter routing
spring.cloud.gateway.server.webflux.routes[1].id=microserviceadopter
spring.cloud.gateway.server.webflux.routes[1].uri=lb://microserviceadopter
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/adopter/**

#Microserviceadoptionrequest routing
spring.cloud.gateway.server.webflux.routes[2].id=microserviceadoptionrequest
spring.cloud.gateway.server.webflux.routes[2].uri=lb://microserviceadoptionrequest
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/adoption/**